// leave off @2x/@3x
const images = {
  // logo: require('../Images/ir.png'),
  // clearLogo: require('../Images/top_logo.png'),
  // launch: require('../Images/launch-icon.png'),
  // ready: require('../Images/your-app.png'),
  // ignite: require('../Images/ignite_logo.png'),
  // igniteClear: require('../Images/ignite-logo-transparent.png'),
  // tileBg: require('../Images/tile_bg.png'),
  // background: require('../Images/BG.png'),
  // buttonBackground: require('../Images/button-bg.png'),
  // api: require('../Images/Icons/icon-api-testing.png'),
  // components: require('../Images/Icons/icon-components.png'),
  // deviceInfo: require('../Images/Icons/icon-device-information.png'),
  // faq: require('../Images/Icons/faq-icon.png'),
  // home: require('../Images/Icons/icon-home.png'),
  // theme: require('../Images/Icons/icon-theme.png'),
  // usageExamples: require('../Images/Icons/icon-usage-examples.png'),
  // chevronRight: require('../Images/Icons/chevron-right.png'),
  // hamburger: require('../Images/Icons/hamburger.png'),
  // backButton: require('../Images/Icons/back-button.png'),
  // closeButton: require('../Images/Icons/close-button.png'),
  qr: require("../../Assets/Images/qr.png"),
  small_circle_avatar: require("../../Assets/Images/small_circle_avatar.png"),
  loading: require("../../Assets/Images/loading.gif"),
  cancel: require("../../Assets/Images/cancel.png"),
  qrcode: require("../../Assets/Images/qrcode.png"),
  addImage: require("../../Assets/Images/addImage.png"),
  assetAvatar: require("../../Assets/Images/chair.png"),
  zoneAvatar: require("../../Assets/Images/house.png"),
  asset_pic: require("../../Assets/Images/asset.png"),
  airConditioner: require("../../Assets/Images/air-conditioner.png"),
  checked: require("../../Assets/Images/checked.png"),
  unchecked: require("../../Assets/Images/unchecked.png"),
  redChair: require("../../Assets/Images/redchair.png"),
  zone_pic1: require("../../Assets/Images/zone1.png"),
  zone_pic2: require("../../Assets/Images/zone2.png"),
  zone_pic3: require("../../Assets/Images/zone3.png"),
  no_avatar: require("../../Assets/Images/no_avatar.png"),
  flag: require("../../Assets/Images/flag.png"),
  close_new_report: require("../../Assets/Images/close_new_report.png"),
  close_new_report_2x: require("../../Assets/Images/close_new_report_2x.png"),
  close_new_report_3x: require("../../Assets/Images/close_new_report_3x.png"),
  zone: require('../../Assets/Images/zone.png'),
  checked_box: require('../../Assets/Images/checked_box.png'),
  checked_box_2x: require('../../Assets/Images/checked_box_2x.png'),
  checked_box_3x: require('../../Assets/Images/checked_box_3x.png'),
  unchecked_box: require('../../Assets/Images/unchecked_box.png'),
  unchecked_box_2x: require('../../Assets/Images/unchecked_box_2x.png'),
  unchecked_box_3x: require('../../Assets/Images/unchecked_box_3x.png'),
  should: require('../../Assets/Images/should.png'),
  //should_2x: require('../../Assets/Images/should_2x.png'),
  //should_3x: require('../../Assets/Images/should_3x.png'),
  must: require('../../Assets/Images/must.png'),
  in_progress: require("../../Assets/Images/in-progress.png"),
  resolved: require("../../Assets/Images/resolved.png"),
  new: require("../../Assets/Images/new.png"),
  //must_2x: require('../../Assets/Images/must_2x.png'),
  //must_3x: require('../../Assets/Images/must_3x.png'),
  close_image: require('../../Assets/Images/close_image.png'),
  close_image_2x: require('../../Assets/Images/close_image_2x.png'),
  close_image_3x: require('../../Assets/Images/close_image_3x.png'),
  add_note_3x: require('../../Assets/Images/add_note_3x.png'),
  close_note_3x: require('../../Assets/Images/close_note_3x.png'),
  search_icon: require('../../Assets/Images/search_icon.png'), 
  search_icon_2x: require('../../Assets/Images/search_icon_2x.png'),
  search_icon_3x: require('../../Assets/Images/search_icon_3x.png'),  
  table: require('../../Assets/Images/table.png'),
  filter: require('../../Assets/Images/filter.png'),
  report_flag: require('../../Assets/Images/report_flag.png'),
  close_modal: require('../../Assets/Images/close_modal.png'),
  checked_modal: require('../../Assets/Images/checked_modal.png'),
  // should: require("../../Assets/Images/should.png"),
  // should_2x: require("../../Assets/Images/should_2x.png"),
  // should_3x: require("../../Assets/Images/should_3x.png"),
  // must: require("../../Assets/Images/must.png"),
  // must_2x: require("../../Assets/Images/must_2x.png"),
  // must_3x: require("../../Assets/Images/must_3x.png"),
  menu_bar_3x: require("../../Assets/Images/menu_bar_3x.png"),
  request_3x: require("../../Assets/Images/request_3x.png"),
  non_request_3x: require("../../Assets/Images/non_request_3x.png"),
  scan_qr: require("../../Assets/Images/scan_QR.png"),
  scan_qr_black: require("../../Assets/Images/scan_QR_black.png"),
  my_report: require("../../Assets/Images/my_report.png"),
  my_report_black: require("../../Assets/Images/my_report_black.png"),
  zone_drawer: require("../../Assets/Images/zone_drawer.png"),
  zone_drawer_black: require("../../Assets/Images/zone_drawer_black.png"),
  asset_drawer: require("../../Assets/Images/asset_drawer.png"),
  asset_drawer_black: require("../../Assets/Images/asset_drawer_black.png"),
  logout_black: require("../../Assets/Images/logout_black.png"),
  white_flag: require("../../Assets/Images/white_flag.png"),
  reset: require("../../Assets/Images/reset.png"),
  submit_success: require("../../Assets/Images/submit_success.png"),
  storage_pic: require("../../Assets/Images/storage.png"),
  close_circle_outline: require("../../Assets/Images/close_circle_outine.png"),
  percent: require("../../Assets/Images/percent.png"),
  status_new: require("../../Assets/Images/status_new.png"),
  status_in_progress: require("../../Assets/Images/in_progress.png"),
  status_resolved: require("../../Assets/Images/resolved.png"),
  check_on: require("../../Assets/Images/check_on.png"),
  check_off: require("../../Assets/Images/check_off.png"),
  bad: require('../../Assets/Images/bad_3x.png'),
  good: require('../../Assets/Images/good_3x.png'),
  unknown: require('../../Assets/Images/unknown.png')
};

export default images;
